"""init schema

Revision ID: f8227c7e035d
Revises:
Create Date: 2025-09-12 08:25:12.742286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8227c7e035d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('householder', sa.String(length=128), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('zone', sa.String(length=1), nullable=False),
    sa.Column('house_id', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_households_email'), 'households', ['email'], unique=False)
    op.create_index(op.f('ix_households_house_id'), 'households', ['house_id'], unique=True)
    op.create_index(op.f('ix_households_serial_number'), 'households', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_households_serial_number'), table_name='households')
    op.drop_index(op.f('ix_households_house_id'), table_name='households')
    op.drop_index(op.f('ix_households_email'), table_name='households')
    op.drop_table('households')
    # ### end Alembic commands ###
